apiVersion: batch/v1
kind: Job # Deployment will automatically restart when killed. Use Pod if not needed
metadata:
  labels:
    k8s-app: research
  generateName: xyang-covid-job
  namespace: ecepxie
spec:
  template:
    metadata:
      labels:
        k8s-app: research
    spec:
      restartPolicy: Never
      containers:
      - name: research
        image: gitlab-registry.nautilus.optiputer.net/vamsirk/research-containers
        imagePullPolicy: Always
        workingDir: /ceph/COVID-19/COVID-Net-
        command: ["/bin/bash","train.sh"]
        resources:
          requests:
            memory: "24Gi"
            cpu: "2"
            nvidia.com/gpu: 1
          limits:
            memory: "24Gi"
            cpu: "2"
            nvidia.com/gpu: 1
        volumeMounts:
        - mountPath: /ceph
          name: xyang-volume
      volumes:
        - name: xyang-volume
          persistentVolumeClaim:
            claimName: xyang-volume
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: gpu-type
                operator: In # Use NotIn for other types
                values:
                - 1080Ti